### ISSUE TITLE
Ошибка аргументов sharp resize в assertView

### ISSUE THREAD

**Issue by hheimerd** [gemini-testing/testplane#1006]
### Verify latest release

- [ ] I verified that the issue exists in the latest Hermione release

### Reproduction steps

Шаги воспроизведения не подскажу, но знаю, как пофиксить.

### Actual Behavior

Падает ошибка
"Expected integer for top but received 0.5 of type number"
at Object.invalidParameterError (/sharp@0.32.6/node_modules/sharp/lib/is.js:135:10)
    at Sharp.<anonymous> (/sharp@0.32.6/node_modules/sharp/lib/resize.js:475:16)
    at Array.forEach (<anonymous>)
    at Sharp.extract (/sharp@0.32.6/node_modules/sharp/lib/resize.js:470:38)
    at Image.crop (/hermione@8.9.5/node_modules/hermione/src/image.js:37:19)
    at async Viewport.handleImage (/hermione@8.9.5/node_modules/hermione/src/browser/screen-shooter/viewport/index.js:47:9)
    at async ScreenShooter.capture (/hermione@8.9.5/node_modules/hermione/src/browser/screen-shooter/index.js:21:9)
    at async assertView (/hermione@8.9.5/node_modules/hermione/src/browser/commands/assert-view/index.js:82:29)

### Expected Behavior

Ошибки быть не должно

### Which Node.js version are you using?

20.10.0

**Comment by hheimerd** [comment]
Нужно в функцию [_sanitize](https://github.com/gemini-testing/testplane/blob/1c88bef7f24444196d8c9e6dd5ef999f72325f89/src/browser/screen-shooter/viewport/index.js#L78) добавить Math.floor/ceil. Тут еще встает вопрос совместимости таких изменений, можно округлять возле вызова resize, но вроде как метод _sanitize должен делать значения безопасными.
